### ISSUE TITLE
ansys.dpf.post setup is failing

### ISSUE THREAD

**Issue by sarunarthy** [pyansys/pydpf-post#58]
I just trying with simple example of loading an example and print the solution and ending up with following error (posted the call trace below).  Can someone help in setting up the right environment

runfile('D:/Tubular_HX/Py_Ansys_resources/SamplePythonScript.py', wdir='D:/Tubular_HX/Py_Ansys_resources')
Hello world
Traceback (most recent call last):

  File "D:\Tubular_HX\Py_Ansys_resources\SamplePythonScript.py", line 12, in <module>
    solution = post.load_solution(simple_bar)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\dpf\post\post_utility.py", line 45, in load_solution
    _model = Model(data_sources)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\dpf\core\model.py", line 48, in __init__
    server = dpf.core._global_server()

  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\dpf\core\server.py", line 83, in _global_server
    start_local_server()

  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\dpf\core\server.py", line 226, in start_local_server
    server = DpfServer(

  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\dpf\core\server.py", line 343, in __init__
    self._server_id = launch_dpf(ansys_path, ip, port, docker_name=docker_name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\dpf\core\server.py", line 599, in launch_dpf
    process = _run_launch_server_process(ansys_path, ip, port, docker_name)

  File "C:\ProgramData\Anaconda3\lib\site-packages\ansys\dpf\core\server.py", line 569, in _run_launch_server_process
    process = subprocess.Popen(run_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

FileNotFoundError: [WinError 2] The system cannot find the file specified

![PY_dpf_post_error](https://user-images.githubusercontent.com/66618364/154308009-09374e5a-59e6-436c-8262-41864b48cd3b.jpg)

**Comment by PProfizi** [comment]
Hi @sarunarthy , is the problem still there? Looks to me as if the server fails to start, and with this error this could be because it does not find the executable or some other necessary file. Could you look at your environment variables when launching this script?

**Comment by sarunarthy** [comment]
Resolved after installing right version of Ansys
